Added simple markers to represent start, end and stopovers
Greennav/GreenNav pull request #48
Opened 2017-03-29 09:13 UTC by hnrqer

#47

2017-03-29 09:19 UTC, hnrqer commented
This is a small sample how markers would look like.
![markers](https://cloud.githubusercontent.com/assets/1770506/24447305/bdf183a0-1470-11e7-8a8f-20918f803c7f.png)

Later we can choose images to replace the circles.

In this feature, only start (GREEN circle) and end (RED circle) markers are functional.
The blue circle I generated by the code by inserting a coordinate in between them.

ATM in the head solution, not even stopovers are being plotted, so when (and if) the solution #46 is merged, stopovers can also be easily added, as the function created supports more than one mark as input.

2017-03-30 11:46 UTC, hnrqer commented
Recommend me nice icons, so that I can integrate in the solution

2017-03-30 19:31 UTC, fabianbormann requested changes
in the old polymer implementation (branch) we had already icons for waypoints. Could you improve your PR to use this old markers (or any other icon markers) ?

2017-03-30 19:31 UTC, fabianbormann commented on src/components/GreenNavMap.js
> +      const circle = new ol.geom.Circle(el, 0.0001);
0.0001 sounds like a magic number 😉  .. could you add a constant or variable circleWidth = 0.0001; above?

2017-03-30 19:31 UTC, fabianbormann commented on src/components/GreenNavMap.js
> +    markersCoordinate.forEach(function(el, i) {
In my opinion "getMarkerFeatures" and "markerCoordinates" sound better..  
subsequently "el" should become "markerCoordinate" to increase the readability 😊

2017-03-30 22:08 UTC, hnrqer commented
I will make the changes and add the icons.

2017-04-01 00:27 UTC, hnrqer commented
Can you please check the solution now? I created the .svg files representing the markers.

Check this out!
![marker icons](https://cloud.githubusercontent.com/assets/1770506/24573341/55b2c538-1682-11e7-9d91-8ffeed0a2761.png)

2017-04-01 15:07 UTC, ar5had reviewed
Looks Very nice.. :+1:  Can you choose a bit dull variant of these colors and shorten the size of icons? IMHO they are quite bright/warm and big.  :)

2017-04-01 15:49 UTC, hnrqer commented
Thanks! The green color was actually the same from the GreenNav logo.

Do you have suggestions regarding the color's pallete? I'm not sure the ones specified in http://greennav.io/development/design-style-guide/ would make it obvious what stop waypoint is, and what a stopover point is.

2017-10-11 17:38 UTC, fabianbormann approved these changes

2020-06-10 15:35 UTC, closed without merging